import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import './globals.css';
import { nunitoSans, raleway } from '@/fonts';
import HeaderMain from '@/components/ui/layout/HeaderMain';
import FooterMain from '@/components/ui/layout/FooterMain';

export const metadata: Metadata = {
  title: 'Theo Ribeiro | Cinematographer',
  description: 'Generated by create next app',
};
interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html
      lang="en"
      className={`${raleway.variable} ${nunitoSans.variable}`}
      data-theme="theo"
    >
      <body
        className={`grid min-h-screen min-w-72 grid-cols-1 grid-rows-[auto_1fr_auto] px-3 font-sans antialiased sm:px-5`}
      >
        <HeaderMain />
        <main>{children}</main>
        <FooterMain />
      </body>
    </html>
  );
}
